CREATE TABLE IF NOT EXISTS products(id INTEGER PRIMARY KEY,name TEXT NOT NULL,category TEXT NOT NULL,price INTEGER NOT NULL,stock INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS users(id TEXT PRIMARY KEY,name TEXT NOT NULL,email TEXT UNIQUE NOT NULL,password_hash TEXT NOT NULL,created_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS sessions(token TEXT PRIMARY KEY,user_id TEXT NOT NULL,created_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS orders(id TEXT PRIMARY KEY,user_id TEXT NOT NULL,total INTEGER NOT NULL,status TEXT NOT NULL,created_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS order_items(id INTEGER PRIMARY KEY AUTOINCREMENT,order_id TEXT NOT NULL,product_id INTEGER NOT NULL,quantity INTEGER NOT NULL,price INTEGER NOT NULL);
INSERT OR IGNORE INTO products(id,name,category,price,stock) VALUES
(1,'Nova X1 Ultra','Tech',79999,18),(2,'Vertex 14','Computing',64999,12),(3,'AeroSound Pro','Audio',8999,25),(4,'Pulse Watch 4','Wearables',12999,20),
(5,'Orbit Mechanical','Desk',6999,30),(6,'LumaCam 4K','Creator',18999,10),(7,'Flux Mini','Tech',3499,40),(8,'Arc Pad','Computing',45999,14);
